export const CATEGORY_ADD='category/add'
export const CATEGORY_DONE='category/done'
export const SET_ADD_CATEGORIES='category/set_add_categories'

export const GETPAGE_START='category/getPage_start'
export const GETPAGE_DONE='category/getPage_done'
export const SET_PAGE='category/setPage'
export const SHOW_MODAL='category/showModal'
export const HIDE_MODAL='category/hideModal'
export const SET_INPUT_PID='category/setInputPid'
export const SET_INPUT_NAME='category/setInputName'
export const UPDATE_START='category/update_start'
export const UPDATE_DONE='category/update_done'